# This is a basic workflow to help you get started with Actions

name: Check Python Wheels

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}
      PYTHON_CMD: "python${{ matrix.python-version }}"

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        python-version: ['2.7']
        compiler: ['gcc', 'clang']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build & Install
        run: |
          ${PYTHON_CMD} setup.py build
          sudo ${PYTHON_CMD} setup.py install

      - name: script
        run: sh -x scripts/do-test.sh
